### ISSUE TITLE
`GivenAndUsing` rule duplicates `using` keyword when explicitly passing a `using` param

### ISSUE THREAD

**Issue by mrdziuban** [arktekk/scala3-scalafix#30]
Thank you for these rules, it makes the migration to new Scala 3 syntax a lot simpler!

I've found that the `GivenAndUsing` rule can produce invalid syntax when existing code is already passing a `using` param explicitly.

For example given this code:

```scala
def test(using i: Int): Int = i

test(using 1)
```

The `GivenAndUsing` rule rewrites it to this:

```scala
def test(using i: Int): Int = i

// Note duplicated `using` keyword here
test(using using 1)
```

I'm guessing something around [here](https://github.com/arktekk/scala3-scalafix/blob/main/rules/src/main/scala/fix/GivenAndUsing.scala#L53-L54) needs to check whether there's already a `using` keyword?

**Comment by ingarabr** [comment]
It's awesome that you found them useful and I'm happy that they're in use :-)

It looks like you're on to something where we need to add a guard against being a `using` (something like `_.is[Mod.Using]`). Could you look into it and create a PR for it?

**Comment by mrdziuban** [comment]
> Could you look into it and create a PR for it?

Sure thing, just opened #31
